/********************************************************************
 *  WARNING: This file is generated by code, edit at your own risk  *
 ********************************************************************/

#include "type_erasure.h"
